/**
 * AuditPage — public read-only view of a CACFP claim snapshot.
 * No login required. Accessible via /audit/:token
 * Generated by sponsors via "Create Audit Link" on the Claims page.
 */

import { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import api from '../../services/api';

const MONTH_LABELS = ['January','February','March','April','May','June',
                      'July','August','September','October','November','December'];

function fmtMonth(str) {
  if (!str) return '';
  const [y, m] = str.split('-');
  return `${MONTH_LABELS[parseInt(m, 10) - 1]} ${y}`;
}

function fmt$(n) {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n || 0);
}

function fmtNum(n) {
  return (n || 0).toLocaleString('en-US');
}

function fmtDate(iso) {
  if (!iso) return '';
  return new Date(iso).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
}

function totalMeals(mealTotals) {
  if (!mealTotals) return 0;
  return Object.values(mealTotals).reduce((s, t) => s + (t.tier1 || 0) + (t.tier2 || 0), 0);
}

// ─── Status badge ─────────────────────────────────────────────────────────────
function StatusPill({ status }) {
  const cfg = {
    ready:         { label: 'Ready',   bg: '#d1fae5', color: '#065f46' },
    needs_review:  { label: 'Review',  bg: '#fef9c3', color: '#854d0e' },
    cannot_submit: { label: 'Blocked', bg: '#fee2e2', color: '#991b1b' },
  }[status] || { label: status, bg: '#f3f4f6', color: '#374151' };
  return (
    <span style={{
      background: cfg.bg, color: cfg.color,
      padding: '3px 10px', borderRadius: 20,
      fontSize: 11, fontWeight: 700
    }}>{cfg.label}</span>
  );
}

// ─── Main page ────────────────────────────────────────────────────────────────
export default function AuditPage() {
  const { token } = useParams();
  const [data,    setData]    = useState(null);
  const [loading, setLoading] = useState(true);
  const [error,   setError]   = useState(null);

  useEffect(() => {
    api.get(`/audit/${token}`)
      .then(({ data }) => setData(data))
      .catch(err => setError(err.response?.data?.error || 'Unable to load audit data.'))
      .finally(() => setLoading(false));
  }, [token]);

  if (loading) return (
    <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#f9fafb' }}>
      <div style={{ textAlign: 'center', color: '#6b7280' }}>
        <div style={{ fontSize: 32, marginBottom: 12 }}>🔍</div>
        <div style={{ fontWeight: 700, fontSize: 16 }}>Loading audit data…</div>
      </div>
    </div>
  );

  if (error) return (
    <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#f9fafb' }}>
      <div style={{ textAlign: 'center', maxWidth: 400 }}>
        <div style={{ fontSize: 40, marginBottom: 12 }}>⚠️</div>
        <div style={{ fontWeight: 800, fontSize: 18, color: '#111827', marginBottom: 6 }}>
          {error.includes('expired') ? 'Audit Link Expired' : 'Link Not Found'}
        </div>
        <div style={{ fontSize: 14, color: '#6b7280' }}>{error}</div>
        {error.includes('expired') && (
          <div style={{ marginTop: 12, fontSize: 13, color: '#6b7280' }}>
            Ask your sponsor to generate a new audit link from their Claims page.
          </div>
        )}
      </div>
    </div>
  );

  const score    = data.readinessScore || 0;
  const isReady  = score >= 90 && (data.sitesCannotSubmit || 0) === 0;
  const scoreColor = isReady ? '#059669' : score >= 60 ? '#d97706' : '#dc2626';
  const breakdown  = data.breakdown || {};
  const lossReasons = (data.items || [])
    .filter(i => i.status !== 'ready')
    .slice(0, 3)
    .map(i => i.siteName);

  return (
    <div style={{ minHeight: '100vh', background: '#f3f4f6' }}>

      {/* ── Header ── */}
      <div style={{ background: '#4f46e5', color: '#fff', padding: '0' }}>
        <div style={{ maxWidth: 900, margin: '0 auto', padding: '20px 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div>
            <div style={{ fontSize: 20, fontWeight: 800 }}>CACFPLink</div>
            <div style={{ fontSize: 12, opacity: 0.8, marginTop: 2 }}>Read-Only Audit View</div>
          </div>
          <div style={{
            background: 'rgba(255,255,255,0.15)', borderRadius: 20,
            padding: '4px 14px', fontSize: 11, fontWeight: 700, letterSpacing: 0.5
          }}>
            🔒 AUDITOR ACCESS
          </div>
        </div>
      </div>

      <div style={{ maxWidth: 900, margin: '0 auto', padding: '28px 24px' }}>

        {/* ── Claim identity ── */}
        <div style={{
          background: '#fff', borderRadius: 14, padding: '24px 28px',
          border: '1px solid #e5e7eb', marginBottom: 20
        }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12 }}>
            <div>
              <div style={{ fontSize: 11, fontWeight: 700, color: '#9ca3af', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 6 }}>
                CACFP Claim Summary
              </div>
              <div style={{ fontSize: 22, fontWeight: 800, color: '#111827' }}>
                {data.orgName || data.stateName + ' Sponsor'}
              </div>
              <div style={{ fontSize: 14, color: '#6b7280', marginTop: 4 }}>
                {fmtMonth(data.claimMonth || data.claim_month)} · {data.stateName} CACFP Program
              </div>
            </div>
            <div style={{ textAlign: 'right' }}>
              <div style={{ fontSize: 11, color: '#9ca3af', marginBottom: 4 }}>Generated</div>
              <div style={{ fontSize: 13, fontWeight: 600, color: '#374151' }}>
                {fmtDate(data.generatedAt)}
              </div>
              <div style={{ fontSize: 11, color: '#9ca3af', marginTop: 6 }}>Expires</div>
              <div style={{ fontSize: 13, fontWeight: 600, color: '#374151' }}>
                {fmtDate(data.expires_at)}
              </div>
            </div>
          </div>
        </div>

        {/* ── 3 summary cards ── */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 14, marginBottom: 20 }}>
          {[
            { label: 'Estimated Reimbursement', value: fmt$(data.estimatedReimbursement), color: '#059669' },
            { label: 'Claim Readiness',         value: `${score}%`,                       color: scoreColor },
            { label: 'Sites Ready',             value: `${data.sitesReady || 0} / ${data.totalSites || 0}`, color: '#4f46e5' },
          ].map(card => (
            <div key={card.label} style={{
              background: '#fff', borderRadius: 12, padding: '18px 20px',
              border: '1px solid #e5e7eb'
            }}>
              <div style={{ fontSize: 11, fontWeight: 700, color: '#9ca3af', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8 }}>
                {card.label}
              </div>
              <div style={{ fontSize: 26, fontWeight: 800, color: card.color }}>
                {card.value}
              </div>
            </div>
          ))}
        </div>

        {/* ── Meal Breakdown ── */}
        {Object.keys(breakdown).length > 0 && (
          <div style={{
            background: '#fff', borderRadius: 14, border: '1px solid #e5e7eb',
            padding: '20px 24px', marginBottom: 20
          }}>
            <div style={{ fontSize: 14, fontWeight: 700, color: '#111827', marginBottom: 14 }}>
              Meal Type Breakdown
            </div>
            <div style={{ display: 'flex', gap: 0, flexWrap: 'wrap' }}>
              {Object.entries(breakdown).filter(([, v]) => v > 0).map(([type, amt], i, arr) => (
                <div key={type} style={{
                  flex: 1, minWidth: 100,
                  padding: '8px 20px',
                  borderRight: i < arr.length - 1 ? '1px solid #e5e7eb' : 'none'
                }}>
                  <div style={{ fontSize: 11, fontWeight: 600, color: '#9ca3af', textTransform: 'capitalize', marginBottom: 4 }}>
                    {type}
                  </div>
                  <div style={{ fontSize: 18, fontWeight: 700, color: '#4f46e5' }}>
                    {fmt$(amt)}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ── Site table ── */}
        <div style={{
          background: '#fff', borderRadius: 14, border: '1px solid #e5e7eb',
          overflow: 'hidden', marginBottom: 20
        }}>
          <div style={{ padding: '16px 24px', borderBottom: '1px solid #f3f4f6' }}>
            <div style={{ fontSize: 14, fontWeight: 700, color: '#111827' }}>
              Site Details — {fmtMonth(data.claimMonth || data.claim_month)}
            </div>
          </div>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ background: '#f9fafb', borderBottom: '1px solid #f3f4f6' }}>
                {['Site', 'Total Meals', 'Status', 'Est. Reimbursement'].map(h => (
                  <th key={h} style={{
                    padding: '10px 20px', textAlign: h === 'Site' ? 'left' : 'right',
                    fontSize: 11, fontWeight: 700, color: '#6b7280', textTransform: 'uppercase', letterSpacing: 0.5
                  }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {(data.items || []).map((item, i) => (
                <tr key={item.siteId} style={{ borderBottom: '1px solid #f9fafb', background: i % 2 === 0 ? '#fff' : '#fafafa' }}>
                  <td style={{ padding: '12px 20px', fontSize: 13, fontWeight: 600, color: '#111827' }}>
                    {item.siteName}
                  </td>
                  <td style={{ padding: '12px 20px', textAlign: 'right', fontSize: 13, color: '#374151' }}>
                    {fmtNum(totalMeals(item.mealTotals))}
                  </td>
                  <td style={{ padding: '12px 20px', textAlign: 'right' }}>
                    <StatusPill status={item.status} />
                  </td>
                  <td style={{ padding: '12px 20px', textAlign: 'right', fontSize: 13, fontWeight: 700, color: '#4f46e5' }}>
                    {fmt$(item.estimatedReimbursement)}
                  </td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr style={{ background: '#ede9fe', borderTop: '2px solid #ddd6fe' }}>
                <td style={{ padding: '12px 20px', fontSize: 13, fontWeight: 700, color: '#111827' }}>Total</td>
                <td />
                <td />
                <td style={{ padding: '12px 20px', textAlign: 'right', fontSize: 15, fontWeight: 800, color: '#4f46e5' }}>
                  {fmt$(data.estimatedReimbursement)}
                </td>
              </tr>
            </tfoot>
          </table>
        </div>

        {/* ── Issues section ── */}
        {(data.sitesCannotSubmit > 0 || data.sitesNeedsReview > 0) && (
          <div style={{
            background: '#fffbeb', border: '1px solid #fde68a',
            borderRadius: 14, padding: '20px 24px', marginBottom: 20
          }}>
            <div style={{ fontSize: 14, fontWeight: 700, color: '#92400e', marginBottom: 12 }}>
              ⚠ Issues Requiring Attention
            </div>
            {(data.items || []).filter(i => i.status !== 'ready').map(item => (
              <div key={item.siteId} style={{ marginBottom: 12 }}>
                <div style={{ fontSize: 13, fontWeight: 700, color: '#374151' }}>
                  {item.siteName} — <StatusPill status={item.status} />
                </div>
                {(item.errors || []).map((e, i) => (
                  <div key={i} style={{ fontSize: 12, color: '#92400e', marginTop: 4, paddingLeft: 12 }}>
                    • {e.message}
                  </div>
                ))}
                {item.checklist?.mealCounts === false && (
                  <div style={{ fontSize: 12, color: '#92400e', marginTop: 4, paddingLeft: 12 }}>
                    • Meal counts not submitted this month
                  </div>
                )}
                {item.checklist?.documents === false && (
                  <div style={{ fontSize: 12, color: '#92400e', marginTop: 4, paddingLeft: 12 }}>
                    • Required documents missing or expired
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        {/* ── Footer ── */}
        <div style={{ textAlign: 'center', padding: '24px 0', borderTop: '1px solid #e5e7eb', marginTop: 8 }}>
          <div style={{ fontSize: 13, fontWeight: 600, color: '#9ca3af' }}>
            This is a read-only audit view generated by {data.orgName || 'a CACFP sponsor'} via CACFPLink.
          </div>
          <div style={{ fontSize: 12, color: '#9ca3af', marginTop: 4 }}>
            Estimates only. Actual reimbursement is subject to state agency review. · cacfplink.com
          </div>
          {data.view_count > 1 && (
            <div style={{ fontSize: 11, color: '#d1d5db', marginTop: 6 }}>
              Viewed {data.view_count} times
            </div>
          )}
        </div>

      </div>
    </div>
  );
}
